### ISSUE TITLE
Siroc is getting deprecated

### ISSUE THREAD

**Issue by pi0** [Intevel/convert-gitmoji#1]
You might want to migrate to https://github.com/unjs/unbuild/

**Comment by Intevel** [comment]
https://github.com/Intevel/convert-gitmoji/commit/fef82d5f934f4b75231f5df2f47642ae1823fd20

**Comment by pi0** [comment]
Thanks. BTW do don't need build.config file. It works just like siroc for auto config. Also check this template (https://github.com/unjs/template/blob/main/package.json), you might want to add `exports`  field.
