### ISSUE TITLE
Possible performance improvements

### ISSUE THREAD

**Issue by pi0** [Intevel/convert-gitmoji#2]
The current version is doing `n` (number of possible gitmojis) replacements that each do a `replaceAll` which iterates over the entire document. We can instead compile a regex (of Object.keys in the map) and match all possible emojies with one regex to replace.

**Comment by Intevel** [comment]
@pi0 Thanks, improved with RegEx in https://github.com/Intevel/convert-gitmoji/commit/d7a5abb41161f907a0cedb5a40e833bec6c952c7
